name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies 
        run: | 
          npm install
          npm install gh-pages
        
      - name: Build and Deploy
        run: |
          npm run build
          ./node_modules/.bin/gh-pages -d build 
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_BASE_URL: ${{ env.REACT_APP_BASE_URL }}
        
